name: ci

on: pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ['3.10', '3.11']
      
    steps:

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Download python versions
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install requirements
        run: pip install -r requirements.txt 
      
      - name: Test data contract in
        run: pytest tests/test_contrato_in.py -v 
              
      - name: Test data contract out
        run: pytest tests/test_contrato_out.py -v